// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('@arco-design/web-vue')['ConfigProvider']
    DBtn: typeof import('./src/components/DBtn.vue')['default']
    DChart: typeof import('./src/components/DChart.vue')['default']
    Dialog: typeof import('./src/components/dialog/Dialog.vue')['default']
    DInput: typeof import('./src/components/DInput.vue')['default']
    DSelect: typeof import('./src/components/DSelect.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    NoData: typeof import('./src/components/status/NoData.vue')['default']
    Notifier: typeof import('./src/components/notify/Notifier.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spin: typeof import('./src/components/status/Spin.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
